// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class WifiIpChangedEvent {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WifiIpChangedEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWifiIpChangedEvent(bb:flatbuffers.ByteBuffer, obj?:WifiIpChangedEvent):WifiIpChangedEvent {
  return (obj || new WifiIpChangedEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWifiIpChangedEvent(bb:flatbuffers.ByteBuffer, obj?:WifiIpChangedEvent):WifiIpChangedEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WifiIpChangedEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

ip():string|null
ip(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
ip(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startWifiIpChangedEvent(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addIp(builder:flatbuffers.Builder, ipOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, ipOffset, 0);
}

static endWifiIpChangedEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createWifiIpChangedEvent(builder:flatbuffers.Builder, ipOffset:flatbuffers.Offset):flatbuffers.Offset {
  WifiIpChangedEvent.startWifiIpChangedEvent(builder);
  WifiIpChangedEvent.addIp(builder, ipOffset);
  return WifiIpChangedEvent.endWifiIpChangedEvent(builder);
}
}
