name: build-staticfs
description: Builds the static filesystem partition and uploads it as an artifact
inputs:
  version:
    required: true
    description: 'Current firmware version'
  skip-checkout:
    description: 'If true, skips checkout'
    required: false
    default: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      if: ${{ !inputs.skip-checkout }}

    - uses: actions/cache@v4
      with:
        path: |
          ~/.platformio/platforms
          ~/.platformio/packages
          ~/.platformio/.cache
        key: pio-${{ runner.os }}-${{ hashFiles('platformio.ini', 'requirements.txt') }}

    - uses: actions/setup-python@v5
      with:
        cache: 'pip'

    - name: Install dependencies
      shell: bash
      run: pip install -r requirements.txt

    - name: Download built frontend
      uses: actions/download-artifact@v4
      with:
        name: frontend
        path: frontend/build/

    - name: Build filesystem partition
      shell: bash
      run: pio run --target buildfs -e fs
      env:
        OPENSHOCK_FW_VERSION: ${{ inputs.version }}
        OPENSHOCK_FW_GIT_REF: ${{ github.ref }}
        OPENSHOCK_FW_GIT_COMMIT: ${{ github.sha }}
        OPENSHOCK_FW_BUILD_DATE: ${{ github.event.head_commit.timestamp }}

    - name: Rename partition binary
      shell: bash
      run: mv .pio/build/fs/littlefs.bin staticfs.bin

    - name: Upload internal filesystem artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware_staticfs
        path: staticfs.bin
        retention-days: 1
        if-no-files-found: error
