name: merge-partitions
description: Merges multiple partitions into a single flashable binary
inputs:
  version:
    description: 'Version of the firmware'
    required: true
  board:
    description: 'Board name to merge partitions for'
    required: true
  skip-checkout:
    description: 'If true, skips checkout'
    required: false
    default: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      if: ${{ !inputs.skip-checkout }}
      with:
        sparse-checkout: |
          scripts
          boards
          chips

    - uses: actions/setup-python@v5
      with:
        cache: 'pip'

    - name: Install dependencies
      shell: bash
      run: pip install -r requirements.txt

    - name: Download static filesystem partition
      uses: actions/download-artifact@v4
      with:
        name: firmware_staticfs

    - name: Download firmware partitions
      uses: actions/download-artifact@v4
      with:
        name: firmware_build_${{ inputs.board }}

    - name: Merge partitions
      shell: bash
      run: |
        python scripts/merge_image.py ${{ inputs.board }}
        mv merged.bin OpenShock_${{ inputs.board }}_${{ inputs.version }}.bin

    - name: Upload merged firmware binary
      uses: actions/upload-artifact@v4
      with:
        name: firmware_merged_${{ inputs.board }}
        path: OpenShock_${{ inputs.board }}_*.bin
        retention-days: 7
        if-no-files-found: error
