name: build-frontend
description: Builds the frontend and uploads it as an artifact
inputs:
  pnpm-version:
    description: 'pnpm version to use'
    required: true
  node-version:
    description: 'NodeJS runtime version to use'
    required: true
  skip-checkout:
    description: 'If true, skips checkout'
    default: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      if: ${{ !inputs.skip-checkout }}
      with:
        sparse-checkout: |
          frontend
        path: ${{ github.repository }}

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - uses: actions/setup-node@v4
      with:
        node-version-file: ./frontend/.nvmrc
        cache: 'pnpm'
        cache-dependency-path: ./frontend/pnpm-lock.yaml

    - name: Install dependencies
      working-directory: ./frontend
      shell: bash
      run: pnpm install --frozen-lockfile --strict-peer-dependencies

    - name: Check
      working-directory: ./frontend
      shell: bash
      run: pnpm run check

    - name: Install playwright
      working-directory: ./frontend
      shell: bash
      run: pnpx playwright install --with-deps

    - name: Test
      working-directory: ./frontend
      shell: bash
      run: pnpm test

    - name: Build
      working-directory: ./frontend
      shell: bash
      run: pnpm run build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend
        path: frontend/build/*
        retention-days: 1
        if-no-files-found: error
