name: cpp-linter

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths: ['**.c', '**.h', '**.cpp', '**.hpp', '.clang-format']
  push:
    paths: ['**.c', '**.h', '**.cpp', '**.hpp', '.clang-format']
  workflow_dispatch: # Manually invoked by user.

jobs:
  get-vars:
    uses: ./.github/workflows/get-vars.yml

  cpp-linter:
    name: C/C++ Linter
    runs-on: ubuntu-latest
    needs: get-vars

    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/build-compilationdb
        with:
          board: OpenShock-Core-V2 # Doesn't matter, just need the compilation database
          skip-checkout: true
      
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          version: 18
          lines-changed-only: diff
          thread-comments: true
          file-annotations: false

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: |
          echo "Some files failed the linting checks!"
        # for actual deployment
        # run: exit 1
